# Site Settings
title: LiyzCj | a blog of Liyanzhe and Guchaojun
email: liyz0912@gmail.com
description: This is a test!
baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
url: "https://www.rossener.com" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: LiYanzhe
user_description: My name is Alex~
disqus_username: liyzcj

# Social Media
# Remove the item if you don't need it
github_username: liyzcj 
facebook_username: alex li
twitter_username: alex
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: alex
    url: /alex/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
